name: update website

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Initialisation
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup environment
      run: pip install -r requirements.txt

    - name: build website
      run: make html

    - name: check links
      run: make linkcheck

    - name: Deploy changes
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/html
